apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
spec:
  type: NodePort
  selector:
    app: gateway-api-pod
  ports:
    - port: 32001
      nodePort: 32001
      targetPort: 80

