apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vssummit-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://g3o5pftxou53w3gfvqyqg6tndmxexh5jex3r72wk2tggg4pdpsqa@dev.azure.com/kenerrysoftwareengineer/VSSummit-2023/_git/vssummit-gitops
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: vssummit-production
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true