apiVersion: v1
kind: Service
metadata:
  name: health-checks-api-service
spec:
  type: NodePort
  selector:
    app: health-check-api-pod
  ports:
    - port: 32002
      nodePort: 32002
      targetPort: 80

