apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
spec:
  type: NodePort
  selector:
    app: stock-api-pod
  ports:
    - port: 32005
      nodePort: 32005
      targetPort: 80

