apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcheck-config-map
data: 
  app.settings.production.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "HealthChecksUi": {
        "HealthChecks": {
          "0": {
            "Name": "Gateway",
            "Uri": "https://production.salesmine.com.br/identity/health"
          },
          "1": {
            "Name": "Principal",
            "Uri": "https://production.salesmine.com.br/identity/health"
          },
          "2": {
            "Name": "Order",
            "Uri": "https://production.salesmine.com.br/identity/health"
          },
          "3": {
            "Name": "Stock",
            "Uri": "https://production.salesmine.com.br/identity/health"
          }
        }
      }
    }
