apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  type: NodePort
  selector:
    app: order-api-pod
  ports:
    - port: 32003
      nodePort: 32003
      targetPort: 80

