apiVersion: v1
kind: Service
metadata:
  name: principal-api-service
spec:
  type: NodePort
  selector:
    app: principal-api-pod
  ports:
    - port: 32004
      nodePort: 32004
      targetPort: 80

